version: "3.3"
services:

  postgresql:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: bitnami_keycloak
    ports:
      - "5432:5432"
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    networks:
      - back-tier
    env_file: .env

  app:
    image: dev.usegroup.de:5050/internal/mustangserver:${CI_COMMIT_REF_SLUG}
    ports:
      - "8000:8000"
    networks:
      - back-tier
      - front-tier
    entrypoint: java -jar -D"spring.profiles.active=prod" /opt/mustangserver/mustangserver-${MUSTANG_SERVER_VERSION}.war
    env_file: .env

  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: keycloak/Dockerfile
    ports:
      - "${KEYCLOAK_HTTP_PORT}:8080"
      - "${KEYCLOAK_HTTPS_PORT}:8443"
    networks:
      - back-tier
      - front-tier
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: bitnami1
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: bitnami_keycloak
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: sonar
      KEYCLOAK_DATABASE_SCHEMA: public
    depends_on:
      - postgresql
      - mailhog
    env_file: .env

  mailhog:
    container_name: mailhog
    build:
      context: .
      dockerfile: mailhog/Dockerfile
    ports:
      - "${MAILHOG_SMTP_PORT_EXPOSE}:1025"
      - "${MAILHOG_WEB_PORT_EXPOSE}:8025"
    networks:
      - back-tier
      - front-tier
    env_file: .env


networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  share_data:
    driver: local
  postgresql_data:
    driver: local
  elasticsearch_data:
    driver: local